// Auto-generated by AgentDesk AI
import {
  ContractEventLog,
  ContractEventName,
  DecodedEvent,
  Decoder,
  LogWithTransaction,
  LogWithTransactionAndReceipt,
} from "./interfaces.ts";

function isContractEventLog(event: any): event is ContractEventLog {
  return (event as ContractEventLog).address !== undefined;
}

function isLogWithTransaction(
  event: any,
): event is LogWithTransaction {
  return isContractEventLog(event) && (event as LogWithTransaction).transaction !== undefined;
}

function isLogWithTransactionAndReceipt(
  event: any,
): event is LogWithTransactionAndReceipt {
  return (
    isLogWithTransaction(event) &&
    (event as LogWithTransactionAndReceipt).receipt !== undefined
  );
}

/**
 * Decodes an array of events using the provided decoder.
 * Returns a tuple of decoded and rejected events.
 * Rejected events are those that couldn't be decoded.
 */
export function decodeChainEvents(
  events: any[],
  decoder: Decoder,
  includeEventData: boolean,
): [DecodedEvent[], any[]] {
  const decoded: DecodedEvent[] = [];
  const rejected: any[] = [];

  for (const event of events) {
    if (isContractEventLog(event)) {
      try {
        const decodedEvent = decoder.decodeEvent(event);
        if (decodedEvent === null || decodedEvent === undefined) {
          throw new Error(
            `Failed to decode event: ${JSON.stringify(event)}`,
          );
        }
        if (includeEventData) {
          if (isLogWithTransactionAndReceipt(event)) {
            decodedEvent.eventData = event.receipt?.data;
          } else if (isLogWithTransaction(event)) {
            decodedEvent.eventData = event.transaction?.data;
          }
        }
        decoded.push(decodedEvent);
      } catch (error) {
        rejected.push({ event, reason: String(error) });
      }
    }
  }

  return [decoded, rejected];
}
