// Auto-generated by AgentDesk AI
import { Database } from "../deps.ts";
import { generateCheckpoint } from "../checkpoint/checkpoint.ts";
import { decodeChainEvents } from "../decode.ts";
import { handleEvents } from "../handlers/handle_events.ts";
import { getProcessedBlocksFromDB, getUnprocessedBlocksFromDB } from "../helpers/db_helpers.ts";
import {
  AlertLevel,
  BlockResponse,
  DecodedEvent,
  IndexerConfig,
  LogWithTransaction,
  ProcessingResult,
} from "../interfaces.ts";
import { getDecoder } from "../registry/registry.ts";
import { saveCheckpoint } from "../services/chain_service.ts";
import { updateProcessingStatus } from "../services/processing_service.ts";
import { logger } from "../utils/logger.ts";

interface HealthCheckResult {
  status: "healthy" | "unhealthy";
  checkpoint: number;
  blockHeight: number;
  gap: number;
  alerts: Array<{
    level: AlertLevel;
    message: string;
    context: Record<string, unknown>;
  }>;
}

export async function index(
  config: IndexerConfig,
  db: Database,
  provider: (blockNumber: number) => Promise<BlockResponse>,
): Promise<void> {
  logger.info("Indexer started", {
    chain: config.chainName,
    startBlock: config.startBlock,
    batchSize: config.batchSize,
  });

  updateProcessingStatus(db, "running");

  try {
    while (true) {
      const currentCheckpoint = generateCheckpoint(config, db);

      const unprocessedBlocks = await getUnprocessedBlocksFromDB(
        db,
        currentCheckpoint,
        config.batchSize,
      );

      if (unprocessedBlocks.length === 0) {
        const finalCheckpoint = generateCheckpoint(config, db);
        if (finalCheckpoint === config.startBlock - 1) {
          logger.info(
            `No blocks to process. Next checkpoint will be ${finalCheckpoint + 1}.`,
          );
        }

        await new Promise((resolve) => setTimeout(resolve, config.pollingInterval));
        continue;
      }

      logger.debug("Processing blocks", {
        count: unprocessedBlocks.length,
        from: currentCheckpoint + 1,
        to: unprocessedBlocks[unprocessedBlocks.length - 1].number,
      });

      const processingResults = await Promise.all(
        unprocessedBlocks.map(async (block) => {
          try {
            const blockResponse = await provider(block.number);
            if (!blockResponse || !blockResponse.logs) {
              logger.warn(`No logs found for block ${block.number}`);
              return { blockNumber: block.number, success: false, error: "No logs" };
            }

            const events: LogWithTransaction[] = blockResponse.logs.map(
              (log) => ({
                ...log,
                transaction: { data: log.data },
              }),
            );

            const decoder = getDecoder(config);
            const [decodedEvents, rejectedEvents] = decodeChainEvents(
              events,
              decoder,
              config.includeEventData,
            );

            if (rejectedEvents.length > 0) {
              logger.warn(`Rejected ${rejectedEvents.length} event(s) in block ${block.number}:`, {
                firstFew: rejectedEvents.slice(0, 5),
              });
            }

            if (decodedEvents.length > 0) {
              const handleResult = await handleEvents(config, db, decodedEvents);
              if (!handleResult.success) {
                logger.error(
                  `Failed to handle events for block ${block.number}: ${handleResult.error}`,
                );
                return { blockNumber: block.number, success: false, error: handleResult.error };
              }
            }

            return { blockNumber: block.number, success: true };
          } catch (error) {
            logger.error(`Error processing block ${block.number}:`, error);
            return { blockNumber: block.number, success: false, error: String(error) };
          }
        }),
      );

      const failedBlocks = processingResults.filter((r) => !r.success);
      if (failedBlocks.length > 0) {
        logger.error(`Failed to process ${failedBlocks.length} block(s)`, {
          blocks: failedBlocks.map((r) => r.blockNumber),
        });
        continue;
      }

      const latestBlockNumber = Math.max(...processingResults.map((r) => r.blockNumber));
      await saveCheckpoint(config, db, latestBlockNumber);

      logger.debug(`Checkpoint saved at block ${latestBlockNumber}`);
    }
  } catch (error) {
    logger.error("Fatal error in indexer loop:", error);
    updateProcessingStatus(db, "error", String(error));
  } finally {
    updateProcessingStatus(db, "stopped");
    logger.info("Indexer stopped");
  }
}

export async function checkIndexerHealth(
  config: IndexerConfig,
  db: Database,
  provider: (blockNumber: number) => Promise<BlockResponse>,
): Promise<HealthCheckResult> {
  const currentCheckpoint = generateCheckpoint(config, db);
  let blockHeight = currentCheckpoint;
  let lastError;

  for (let i = 0; i < 5; i++) {
    try {
      const response = await provider(blockHeight + 1);
      if (response && response.number) {
        blockHeight = response.number;
        break;
      }
    } catch (error) {
      lastError = error;
    }
    blockHeight++;
  }

  const gap = blockHeight - currentCheckpoint;
  const alerts: HealthCheckResult["alerts"] = [];

  if (gap > config.alertThreshold) {
    alerts.push({
      level: "critical" as AlertLevel,
      message: `Chain gap is ${gap} blocks (threshold: ${config.alertThreshold})`,
      context: { gap, threshold: config.alertThreshold },
    });
  }

  const processingStatus = db
    .selectFrom("processing_status")
    .selectAll()
    .executeSync();

  if (processingStatus.length > 0) {
    const status = processingStatus[0];
    if (status.status === "error") {
      alerts.push({
        level: "warning" as AlertLevel,
        message: `Indexer is in error state: ${status.error_message ?? "Unknown error"}`,
        context: { status: status.status, errorMessage: status.error_message },
      });
    }
  }

  const rejectedCountResult = db
    .selectFrom("rejected_events")
    .select((eb) => eb.fn.count("id").as("count"))
    .where("created_at", ">=", new Date(Date.now() - 3600_000).toISOString())
    .executeSync();

  const rejectedCount = rejectedCountResult[0]?.count ?? 0;
  if (Number(rejectedCount) > 0) {
    alerts.push({
      level: "warning" as AlertLevel,
      message: `${rejectedCount} rejected event(s) detected in the last hour`,
      context: { rejectedCount: Number(rejectedCount) },
    });
  }

  const status = alerts.some((a) => a.level === "critical") ? "unhealthy" : "healthy";

  logger.debug("Indexer health check completed", {
    status,
    checkpoint: currentCheckpoint,
    blockHeight,
    gap,
    alertCount: alerts.length,
  });

  return {
    status,
    checkpoint: currentCheckpoint,
    blockHeight,
    gap,
    alerts,
  };
}
