// Auto-generated by AgentDesk AI
import { IndexerConfig } from "../interfaces.ts";
import { Database } from "../../deps.ts";
import { logger } from "../utils/logger.ts";

export function generateCheckpoint(
  config: IndexerConfig,
  db: Database,
): number {
  try {
    const result = db
      .selectFrom("processed_blocks")
      .select("block_number")
      .orderBy("block_number", "desc")
      .limit(1)
      .executeSync();

    if (result.length > 0) {
      return result[0].block_number;
    }

    return config.startBlock - 1;
  } catch (error) {
    logger.error("Error generating checkpoint:", error);
    return config.startBlock - 1;
  }
}
