// Auto-generated by AgentDesk AI
import { describe, it, beforeEach } from "node:test";
import assert from "node:assert";
import { generateCheckpoint } from "./checkpoint.ts";
import { IndexerConfig } from "../interfaces.ts";
import { createTestDb, closeTestDb } from "../../test_helpers.ts";

describe("generateCheckpoint", () => {
  let db;
  const baseConfig: IndexerConfig = {
    chainName: "Base",
    rpcUrl: "https://example.com",
    startBlock: 1000,
    batchSize: 100,
    pollingInterval: 1000,
    contractAddresses: [],
    contractNames: [],
    includeEventData: false,
    alertThreshold: 1000,
  };

  beforeEach(() => {
    db = createTestDb();
  });

  afterEach(() => {
    closeTestDb(db);
  });

  it("should return startBlock - 1 when no blocks are processed", () => {
    const checkpoint = generateCheckpoint(baseConfig, db);
    assert.equal(checkpoint, baseConfig.startBlock - 1);
  });

  it("should return the highest processed block number", () => {
    db.sql`INSERT INTO processed_blocks (block_number) VALUES (1500)`.run();
    db.sql`INSERT INTO processed_blocks (block_number) VALUES (1600)`.run();

    const checkpoint = generateCheckpoint(baseConfig, db);
    assert.equal(checkpoint, 1600);
  });

  it("should handle database errors gracefully", () => {
    const invalidDb = {
      selectFrom: () => {
        throw new Error("DB error");
      },
    };

    const checkpoint = generateCheckpoint(baseConfig, invalidDb as any);
    assert.equal(checkpoint, baseConfig.startBlock - 1);
  });
});
