// Auto-generated by AgentDesk AI
import { Database } from "../../deps.ts";
import { IndexerConfig } from "../interfaces.ts";

export async function getUnprocessedBlocksFromDB(
  db: Database,
  currentCheckpoint: number,
  batchSize: number,
): Promise<Array<{ number: number }>> {
  try {
    const result = await db
      .selectFrom("processed_blocks")
      .select("block_number")
      .where("block_number", ">", currentCheckpoint)
      .orderBy("block_number", "asc")
      .limit(batchSize)
      .execute();

    return result.map((row) => ({ number: row.block_number }));
  } catch (error) {
    console.error("Error getting unprocessed blocks:", error);
    return [];
  }
}

export async function getProcessedBlocksFromDB(
  db: Database,
  config: IndexerConfig,
): Promise<number[]> {
  try {
    const result = await db
      .selectFrom("processed_blocks")
      .select("block_number")
      .where("block_number", ">=", config.startBlock)
      .orderBy("block_number", "asc")
      .execute();

    return result.map((row) => row.block_number);
  } catch (error) {
    console.error("Error getting processed blocks:", error);
    return [];
  }
}
