// Auto-generated by AgentDesk AI
import { DecoderFunction, HandlerFunction, IndexerConfig } from "../interfaces.ts";
import { logger } from "../utils/logger.ts";
import { DEFAULT_CONFIG } from "../indexer/config.ts";

const decoderRegistry: Record<string, Record<string, DecoderFunction>> = {};
const handlerRegistry: Record<string, Record<string, HandlerFunction>> = {};

export function registerDecoder(
  contractName: string,
  eventName: string,
  decoder: DecoderFunction,
): void {
  if (!decoderRegistry[contractName]) {
    decoderRegistry[contractName] = {};
  }
  decoderRegistry[contractName][eventName] = decoder;
  logger.debug(`Registered decoder for ${contractName}.${eventName}`);
}

export function registerHandler(
  contractName: string,
  eventName: string,
  handler: HandlerFunction,
): void {
  if (!handlerRegistry[contractName]) {
    handlerRegistry[contractName] = {};
  }
  handlerRegistry[contractName][eventName] = handler;
  logger.debug(`Registered handler for ${contractName}.${eventName}`);
}

export function getDecoder(config: IndexerConfig) {
  const effectiveConfig = { ...DEFAULT_CONFIG, ...config };
  const contractName = effectiveConfig.contractNames[0];
  return {
    decodeEvent: (event: any) => {
      if (!contractName || !decoderRegistry[contractName]) {
        return null;
      }
      const eventName = event.fragment?.name || event.name;
      const decoder = decoderRegistry[contractName]?.[eventName];
      return decoder?.(event) ?? null;
    },
  };
}

export function getHandler(config: IndexerConfig, eventName: string) {
  const effectiveConfig = { ...DEFAULT_CONFIG, ...config };
  const contractName = effectiveConfig.contractNames[0];
  return contractName ? handlerRegistry[contractName]?.[eventName] : null;
}
