// Auto-generated by AgentDesk AI
import { BlockNumber, DecodedEvent, IndexerConfig } from "../interfaces.ts";
import { getHandler } from "../registry/registry.ts";
import { logger } from "../utils/logger.ts";
import { Database } from "../../deps.ts";

export interface HandlerResult {
  success: boolean;
  error?: string;
}

export async function handleEvents(
  config: IndexerConfig,
  db: Database,
  events: DecodedEvent[],
): Promise<HandlerResult> {
  for (const event of events) {
    try {
      const handler = getHandler(config, event.name);
      if (!handler) {
        logger.warn(`No handler found for event ${event.name} on contract ${event.address}`, {
          contract: event.address,
          event: event.name,
        });
        continue;
      }

      const result = await handler(config, db, event);
      if (!result.success) {
        logger.error(
          `Handler failed for event ${event.name} on contract ${event.address}:`,
          result.error,
        );
        return { success: false, error: result.error };
      }
    } catch (error) {
      logger.error(`Error handling event ${event.name}:`, error);
      return { success: false, error: String(error) };
    }
  }

  return { success: true };
}
