// Auto-generated by AgentDesk AI
export const logger = {
  info: (message: string, meta?: Record<string, unknown>) => {
    console.log(JSON.stringify({ level: "info", message, ...(meta && { meta }) }));
  },
  warn: (message: string, meta?: Record<string, unknown>) => {
    console.warn(JSON.stringify({ level: "warn", message, ...(meta && { meta }) }));
  },
  error: (message: string, error?: unknown) => {
    console.error(JSON.stringify({ level: "error", message, error: error instanceof Error ? error.stack : String(error) }));
  },
  debug: (message: string, meta?: Record<string, unknown>) => {
    if (process.env.DEBUG === "true") {
      console.debug(JSON.stringify({ level: "debug", message, ...(meta && { meta }) }));
    }
  },
};
