// Auto-generated by AgentDesk AI
import { IndexerConfig } from "../interfaces.ts";

export const DEFAULT_CONFIG: IndexerConfig = {
  chainName: "Base",
  rpcUrl: "https://example.com",
  startBlock: 1000,
  batchSize: 100,
  pollingInterval: 1000,
  contractAddresses: [],
  contractNames: [],
  includeEventData: false,
  alertThreshold: 1000,
};
