// Auto-generated by AgentDesk AI
export interface IndexerConfig {
  chainName: string;
  rpcUrl: string;
  startBlock: number;
  batchSize: number;
  pollingInterval: number;
  contractAddresses: string[];
  contractNames: string[];
  includeEventData: boolean;
  alertThreshold: number;
}

export interface BlockResponse {
  number: number;
  hash: string;
  parentHash: string;
  timestamp: number;
  logs: ContractEventLog[];
}

export interface ContractEventLog {
  address: string;
  data: string;
  topics: string[];
  blockNumber: number;
  transactionHash: string;
  logIndex: number;
  transaction?: {
    data: string;
  };
  receipt?: {
    data: string;
  };
}

export interface LogWithTransaction extends ContractEventLog {
  transaction: {
    data: string;
  };
}

export interface LogWithTransactionAndReceipt extends LogWithTransaction {
  receipt: {
    data: string;
  };
}

export type BlockNumber = number;

export interface DecodedEvent {
  name: string;
  address: string;
  args: Record<string, unknown>;
  blockNumber: BlockNumber;
  transactionHash: string;
  logIndex: number;
  eventData?: string;
}

export interface EventPayload {
  eventName: string;
  contractAddress: string;
  args: Record<string, unknown>;
}

export type HandlerFunction = (
  config: IndexerConfig,
  db: any,
  event: DecodedEvent,
) => Promise<{ success: boolean; error?: string }>;

export type DecoderFunction = (log: ContractEventLog) => DecodedEvent | null;

export interface DecoderRegistry {
  [key: string]: {
    [eventName: string]: DecoderFunction;
  };
}

export interface HandlerRegistry {
  [key: string]: {
    [eventName: string]: HandlerFunction;
  };
}

export type AlertLevel = "info" | "warning" | "critical";

export interface ProcessingStatus {
  status: "running" | "stopped" | "error";
  errorMessage?: string;
}
